#!/usr/bin/env bash

build() {
  # why do I transpile? can I test my desired outcome?
  pnpm rollup -c rollup.config.js
}

dev() {
  pnpm vite
}

info:bundlesize() {
 build
 tar -c dist | gzip > dist.tar.gz
 du -h dist dist.tar.gz
 rm dist.tar.gz
}

test:lint() {
  pnpm eslint .eslintrc.cjs .
}

test:publint() {
  pnpm publint .
}

test:ts() {
  pnpm tsc
}

test:unit() {
  pnpm vitest test/unit/keyFor.test.js test/unit/socialIcon.test.js "$@"
}

test:() {
  build;
  test:lint;
  test:publint;
  test:ts;
  test:unit --run;
}

"$@"
