#!/usr/bin/env bash

PRETTIER_PATTERN=("./*.js" "src/**" "test/**")

build() {
  pnpm rollup -c rollup.config.js "$@"
}

dev() {
  pnpm vite -c vite.config.js examples/
}

fmt() {
  pnpm prettier -u -w "${PRETTIER_PATTERN[@]}"
}

info:bundlesize() {
 build
 tar -c dist | gzip > dist.tar.gz
 du -h dist dist.tar.gz
 rm dist.tar.gz
}

test:lint() {
  pnpm eslint .eslintrc.cjs .
}

test:publint() {
  build --silent
  pnpm publint .
}

test:fmt() {
  pnpm prettier -u -c "${PRETTIER_PATTERN[@]}"
}

test:ts() {
  pnpm tsc
}

test:unit() {
  build --silent
  pnpm vitest test/unit/*.test.js "$@"
}

test:src() {
  pnpm vitest test/unit/src.test.js "$@"
}

test:codesplitting() {
  build --silent
  ./test/codesplitting.sh
}

test:() {
  set -e

  test:lint;
  test:publint;
  test:fmt;
  test:ts;
  test:unit --run --silent;
  test:codesplitting;

  echo
  echo Passed All Tests

  set +e
}

"$@"
