name: Build, Test, Publish

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/gh-pages'
    name: Test React v${{ matrix.react-version }}
    strategy:
      matrix:
        react-version: [ 16, 17, 18 ]
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install compatible testing library for older react versions
        if: ${{ matrix.react-version }} < 18
        run: pnpm add -D @testing-library/react@12

      - name: Install React v${{ matrix.react-version }}
        run: pnpm i react@${{ matrix.react-version }} react-dom@${{ matrix.react-version }}

      - name: Test build
        run: pnpm run build

      - name: Test React v${{ matrix.react-version }}
        run: pnpm test

  publish:
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: test
    runs-on: ubuntu-latest
    name: Publish Package
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Prepublish
        run: pnpm run prepublish

      - name: Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  example-page:
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: publish
    runs-on: ubuntu-latest
    name: Update Example Page
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'origin/gh-pages'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Save Release Version
        id: release
        run: echo ::set-output name=version::$(pnpm view react-social-icons version)

      - name: Update, Build & Commit Example Site
        run: |
          git pull --no-edit origin v${{steps.release.outputs.version}}
          parcel build examples/index.html --public-url /react-social-icons/
          rm app.*
          cp dist/* .
          git add .
          git commit -m "v${{steps.release.outputs.version}}"
          git push origin gh-pages

