name: Build, Test, Publish

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test React v${{ matrix.react-version }}
    strategy:
      matrix:
        react-version: [15, 16, 17]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: guardian/actions-setup-node@main
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1

      - name: Install React v${{ matrix.react-version }}
        run: npm i react@${{ matrix.react-version }} react-dom@${{ matrix.react-version }} --no-save

      - name: Test build
        run: npm run build

      - name: Test React v${{ matrix.react-version }}
        run: npm test

  publish:
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: test
    runs-on: ubuntu-latest
    name: Publish Package
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: guardian/actions-setup-node@main
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1

      - name: Prepublish
        run: npm run prepublish

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  example-page:
    needs: publish
    runs-on: ubuntu-latest
    name: Update Example Page
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'origin/gh-pages'

      - name: Setup Node
        uses: guardian/actions-setup-node@main
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1

      - name: Save Release Version
        id: release
        run: echo ::set-output name=version::$(npm view react-share-social-icons version)

      - name: Update, Build & Commit Example Site
        run: |
          git pull --no-edit origin v${{steps.release.outputs.version}}
          parcel build examples/index.html --public-url /react-share-social-icons/
          rm app.*
          cp dist/* .
          git add .
          git commit -m "v${{steps.release.outputs.version}}"
          git push origin gh-pages
