name: PR Helper

on:
  pull_request:
    branches: '*'
  workflow_dispatch:
  push:
    branches: '*'

jobs:
  screenshot:
    runs-on: ubuntu-latest
    name: Screenshot
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Take Screenshot
        run: |
          sha="$GITHUB_SHA"

          ./cli build:visual --outDir "/tmp/visual/$sha/dist"

          pnpm vite preview \
            --host 0.0.0.0 \
            --port 4173 \
            --strictPort \
            --open false \
            -c test/visual/vite.config.js \
            "/tmp/visual/$sha" \
            &
          pid=$!

          git fetch origin
          git checkout gh-pages

          echo "status:"
          git status

          scale=2
          network=tiktok

          pnpx playwright screenshot \
            --viewport-size="$((1250 * $scale)), $((400 * $scale))" \
            "http://localhost:4173?network=$network&knobs=false&scale=$scale" \
            "./static/$sha/$network.png"

          pnpx playwright screenshot \
          --full-page \
            "http://localhost:4173?knobs=false&scale=$scale" \
            "./static/$sha/index.png"

          kill $pid

          git add static/
          git \
            -c user.name="screenshots[bot]" \
            -c user.email="screenshots[bot]@users.noreply.github.com" \
            commit \
            -m "screenshots (automated)" \
            --no-verify
          git push origin gh-pages

          git checkout -

          link_networks="https://jaketrent.github.io/react-social-icons/static/$sha/$network.png"
          link_index="https://jaketrent.github.io/react-social-icons/static/$sha/index.png"

          echo "link_networks=$link_networks" >> $GITHUB_OUTPUT
          echo "link_index=$link_index" >> $GITHUB_OUTPUT

      - name: Comment on PR with screenshots
        uses: actions/github-script@v6
        with:
          script: |
            // const link_networks = ${{ steps.vars.outputs.link_networks }}
            // const link_index = ${{ steps.vars.outputs.link_index }}

            const link = "${{ steps.vars.outputs.link_networks }}";
            console.log(link)

            /*
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
                # Screenshots
                <details>
                  <summary>
                    ${link_networks.replace(/^.*\//, '')}
                  </summary>
                  <img
                    src="${link_networks}"
                    alt="screenshot of an updated social network"
                  />
                  <img
                    src="${link_index}"
                    alt="screenshot of all networks"
                  />
                </details>
              `.replace(/^\w+/, '').trim()
            })
            */

#       - name: take screenshot
#         uses: ./.github/actions/screenshot
